{% set name = "ajc27-freemocap-blender-addon" %}
{% set version = "2025.11.1038" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ajc27_freemocap_blender_addon-{{ version }}.tar.gz
  sha256: 11e89be314f579db9e31d0d4d6d16f8d1ca04e20e1f87b59a9da8dd417235c5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - ajc27_freemocap_blender_addon
  commands:
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/freemocap/freemocap_blender_addon
  summary: A Blender Add-on for working with Freemocap Data (based on @ajc27's addon)
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - roaldarbol
